/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("Firefly" , 3,4);
        
        Review firstReview = new Review(" very good","Balqees",5);
        Review secondReview = new Review("good","jack",4);
        Review thirdReview = new Review("bad","Tamer",2);

        System.out.println(restaurant);

        restaurant.addReviews(firstReview);
        restaurant.addReviews(secondReview);
        restaurant.addReviews(thirdReview);

        System.out.println(restaurant.getReviews());
        System.out.println(restaurant);







    }

}
