/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void RestaurantName(){
      Restaurant restaurant = new Restaurant("Firefly" ,3,4);
      assertEquals("Restaurant name: Firefly  Rates : 3.0 price category: 4.0$", restaurant.toString());
    }

    @Test void RestaurantReview(){
        Review review = new Review("very good","Balqees",5);
        assertEquals("Author :  Balqees, rates :  5, notes: very good", review.toString());
    }

    @Test void Reviews(){
        Restaurant restaurant = new Restaurant("Firefly" ,3,4);

        Review firstReview = new Review(" very good","Balqees",5);
        Review secondReview = new Review("good","jack",4);
        Review thirdReview = new Review("bad","Tamer",2);

        restaurant.addReviews(firstReview);
        restaurant.addReviews(secondReview);
        restaurant.addReviews(thirdReview);

        assertEquals("[Author :  Balqees, rates :  5, notes:  very good, Author :  jack, rates :  4, notes: good, Author :  Tamer, rates :  2, notes: bad]",restaurant.getReviews().toString());
    }
}
